import = [
  "~/.dotfiles/alacritty/tomorrow_night_bright.toml"
]

[colors]
# draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12

# [font.normal]
# family = "Ubuntu Mono"

[window]
decorations = "None"
startup_mode = "SimpleFullscreen"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 16
y = 30

[[hints.enabled]]
mouse.enabled = true
command = "open"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
